## CustomDB

Download from the prophet-studio.3steps.cn and upload to the customdb folder.

You can connect to the database and fetch the related records by using the following sql query:

```sql
SELECT relation_type,source_name,source_type,source_id,target_name,target_type,target_id,key_sentence,pmid FROM biomedgps_knowledge_curation WHERE curator = '1635231996@qq.com' AND source_id != 'Unknown:Unknown' AND target_id != 'Unknown:Unknown';
```

### Reformat the curated knowledges as the BioMedGPS format

In [8]:
import click
import pandas as pd

In [13]:
valid_entity_types = [
    "Compound",
    "Disease",
    "Gene",
    "Metabolite",
    "Pathway",
    "Anatomy",
    "Phenotype",
    "PharmacologicClass",
    "BiologicalProcess",
    "CellularComponent",
    "MolecularFunction",
]

In [11]:
import pandas as pd
df = pd.read_csv("customdb_v20240630.tsv", sep="\t")  # 如果是 tab 分隔
df

,relation_type,source_name,source_type,source_id,target_name,target_type,target_id,key_sentence,pmid
0,inhibited_by,MnSOD,Gene,ENTREZ:20656,PM2.5,Compound,MESH:D052638,PM2.5 inhibited Mn superoxide dismutase (MnSOD...,25560372
1,increased_by,TNF-α,Gene,ENTREZ:21926,PM,Compound,MESH:D052638,The results found that PM mice displayed highe...,32270451
2,Hetionet::DrD::Disease:Disease,long COVID,Disease,MONDO:0100233,Endometriosis,Disease,MONDO:0005133,See Figure 1 for a summary of the female repro...,37234076
3,Hetionet::DrD::Disease:Disease,long COVID,Disease,MONDO:0100233,Amenorrhea,Disease,MONDO:0001836,See Figure 1 for a summary of the female repro...,37234076
4,Hetionet::DrD::Disease:Disease,long COVID,Disease,MONDO:0100233,Obesity,Disease,MONDO:0011122,"For example, lipid metabolism disorders and ob...",36071155
...,...,...,...,...,...,...,...,...,...
2332,Hetionet::DdG::Disease:Gene,M-CSF,Gene,ENTREZ:1435,long COVID,Disease,MONDO:0100233,Patients with PCC also had significantly decre...,37717649
2333,Hetionet::DdG::Disease:Gene,IL-1β,Gene,ENTREZ:3553,long COVID,Disease,MONDO:0100233,Patients with PCC also had significantly decre...,37717649
2334,Hetionet::DdG::Disease:Gene,stem cell factor,Gene,ENTREZ:23256,long COVID,Disease,MONDO:0100233,Patients with PCC also had significantly decre...,37717649
2335,Hetionet::DrD::Disease:Disease,COVID-19,Disease,MONDO:0100096,systemic lupus erythematosus,Disease,MONDO:0007915,By looking at the characteristics of each case...,37287442
2336,Hetionet::DrD::Disease:Disease,lymphopenia,Disease,MONDO:0003783,systemic lupus erythematosus,Disease,MONDO:0007915,By looking at the characteristics of each case...,37287442

In [14]:
import pandas as pd

df = pd.read_csv("./customdb_v20240630.tsv", sep="\t")
# Filter all the rows with Unknown:Unknown values in the target_id or source_id columns
df = df[~df["target_id"].str.contains("Unknown:Unknown")]
df = df[~df["source_id"].str.contains("Unknown:Unknown")]
df["idx"] = df.index

# Join the source_type, target_type and relation_type columns
valid_relations = df[
    df["relation_type"].str.contains(".*:+[a-zA-Z]+:[a-zA-Z]+$", regex=True)
    & (
        df["source_type"].apply(lambda x: x in valid_entity_types)
        & df["target_type"].apply(lambda x: x in valid_entity_types)
    )
]
print(f"Valid relations: {valid_relations.shape[0]}")
invalid_relations = df[df["idx"].apply(lambda x: x not in valid_relations.index)]
print(f"Invalid relations: {invalid_relations.shape[0]}")

invalid_relations = invalid_relations.copy()
# Replace 'Protein' with 'Gene' in 'source_type' and 'target_type' columns
invalid_relations["source_type"] = invalid_relations["source_type"].replace(
    "Protein", "Gene"
)
invalid_relations["target_type"] = invalid_relations["target_type"].replace(
    "Protein", "Gene"
)

# Remove all rows which have a invalid source_type or target_type
invalid_relations = invalid_relations[
    (invalid_relations["source_type"].apply(lambda x: x in valid_entity_types))
    & (invalid_relations["target_type"].apply(lambda x: x in valid_entity_types))
].copy()

print(f"Invalid relations after fixing: {invalid_relations.shape[0]}")

invalid_relations["relation_type"] = invalid_relations.apply(
    lambda x: x["relation_type"] + "::" + x["source_type"] + ":" + x["target_type"],
    axis=1,
)

Valid relations: 1164
Invalid relations: 1173
Invalid relations after fixing: 1169

In [15]:
print(invalid_relations["relation_type"].unique())

['inhibited_by::Gene:Compound' 'increased_by::Gene:Compound'
 'increased_by::BiologicalProcess:Disease'
 'associated_with::Pathway:Disease' 'increased_by::Metabolite:Compound'
 'associated_with::Pathway:Metabolite' 'reduced_by::Gene:Compound'
 'associated_with::Anatomy:Compound' 'associated_with::Disease:Gene'
 'increased_by::Gene:Gene' 'activated_by::Pathway:Gene'
 'associated_with::Compound:Disease' 'associated_with::Gene:Compound'
 'reduced_by::BiologicalProcess:Disease' 'reduced_by::Gene:Disease'
 'associated_with::Disease:Compound' 'increased_by::Compound:Disease'
 'induced_by::Disease:Compound' 'activated_by::Pathway:Compound'
 'increased_by::Disease:Compound' 'upregulated_in::Gene:Gene'
 'alleviated_by::Compound:Disease' 'associated_with::Phenotype:Disease'
 'downregulated_in::Gene:Compound' 'induced_by::Pathway:Compound'
 'upregulated_in::Gene:Compound' 'inhibited_by::Pathway:Compound'
 'associated_with::Metabolite:Disease' 'treats::Compound:Pathway'
 'induced_by::Compound:Disease' 'associated_with::Disease:Metabolite'
 'downregulated_in::Compound:Pathway'
 'associated_with::BiologicalProcess:Disease'
 'biomarker::Compound:Disease' 'reduced_by::Metabolite:Compound'
 'associated_with::Gene:Phenotype' 'reduced_by::Compound:Gene'
 'associated_with::Metabolite:Compound'
 'associated_with::BiologicalProcess:Gene'
 'activated_by::Compound:Pathway' 'biomarker::Metabolite:Pathway'
 'associated_with::Phenotype:Gene' 'biomarker::Metabolite:Disease'
 'inhibited_by::BiologicalProcess:Disease'
 'associated_with::Anatomy:Disease' 'biomarker::Gene:Disease'
 'associated_with::BiologicalProcess:Compound'
 'biomarker::BiologicalProcess:Disease'
 'biomarker::CellularComponent:Disease'
 'associated_with::Phenotype:BiologicalProcess'
 'biomarker::Disease:BiologicalProcess'
 'associated_with::Pathway:BiologicalProcess'
 'associated_with::BiologicalProcess:BiologicalProcess'
 'associated_with::CellularComponent:Disease'
 'biomarker::MolecularFunction:Phenotype' 'increased_by::Gene:Disease'
 'associated_with::BiologicalProcess:Metabolite'
 'upregulated_in::Compound:Gene' 'treats::Compound:BiologicalProcess'
 'associated_with::Pathway:Compound'
 'biomarker::BiologicalProcess:Phenotype'
 'associated_with::BiologicalProcess:Anatomy'
 'associated_with::Metabolite:Phenotype'
 'associated_with::BiologicalProcess:Phenotype'
 'biomarker::Gene:Phenotype' 'treats::Compound:Disease'
 'associated_with::Metabolite:BiologicalProcess'
 'reduced_by::Disease:Compound' 'activated_by::Compound:Gene'
 'associated_with::Gene:BiologicalProcess' 'treats::Metabolite:Disease'
 'treats::Compound:Phenotype' 'associated_with::Pathway:Phenotype'
 'biomarker::Pathway:Disease' 'associated_with::Disease:Pathway'
 'associated_with::Disease:Disease' 'associated_with::Gene:Pathway'
 'activated_by::Gene:Compound'
 'associated_with::Disease:BiologicalProcess'
 'increased_by::Metabolite:Gene' 'alleviated_by::Disease:Compound'
 'increased_by::Pathway:Compound' 'reduced_by::Metabolite:Disease'
 'associated_with::Compound:Compound' 'activated_by::Gene:Gene'
 'associated_with::Gene:Disease' 'alleviated_by::Pathway:Compound'
 'increased_by::Compound:Pathway' 'induced_by::Compound:Pathway'
 'downregulated_in::Compound:Compound' 'induced_by::Disease:Disease'
 'reduced_by::Gene:Pathway' 'associated_with::Phenotype:Anatomy'
 'inhibited_by::Pathway:Gene' 'increased_by::Compound:Gene'
 'upregulated_in::Gene:Disease' 'induced_by::BiologicalProcess:Disease'
 'associated_with::Gene:Metabolite' 'treats::Metabolite:Phenotype'
 'caused_by::Disease:Compound' 'inhibited_by::Gene:Gene'
 'inhibited_by::Pathway:Pathway' 'associated_with::Metabolite:Anatomy'
 'biomarker::Gene:Anatomy' 'activated_by::Disease:Compound'
 'biomarker::Gene:Compound' 'associated_with::Gene:Gene'
 'alleviated_by::Gene:Disease' 'induced_by::Gene:Compound'
 'induced_by::Disease:Metabolite' 'upregulated_in::Pathway:Disease'
 'activated_by::Gene:Pathway' 'reduced_by::Compound:Metabolite'
 'associated_with::Compound:Anatomy'
 'inhibited_by::Compound:BiologicalProcess'
 'upregulated_in::Pathway:Compound' 'associated_with::Compound:Pathway'
 'downregulated_in::Pathway:Compound' 'reduced_by::Compound:Disease'
 'biomarker::Metabolite:Compound' 'reduced_by::Disease:Gene'
 'biomarker::Compound:Metabolite' 'increased_by::Phenotype:Gene'
 'biomarker::Disease:Gene' 'inhibited_by::Compound:Pathway'
 'increased_by::Phenotype:Disease' 'increased_by::Gene:Phenotype'
 'associated_with::Anatomy:Phenotype' 'caused_by::Compound:Compound'
 'increased_by::Compound:Phenotype' 'associated_with::Phenotype:Phenotype'
 'biomarker::Anatomy:Disease' 'reduced_by::Pathway:Disease'
 'increased_by::Metabolite:Disease' 'reduced_by::Metabolite:Phenotype'
 'increased_by::Metabolite:Phenotype'
 'downregulated_in::Metabolite:Disease' 'caused_by::Gene:Disease'
 'inhibited_by::Compound:Compound' 'increased_by::Anatomy:Disease'
 'associated_with::Compound:CellularComponent'
 'induced_by::Phenotype:Disease'
 'associated_with::Compound:BiologicalProcess'
 'induced_by::Pathway:BiologicalProcess'
 'induced_by::Compound:BiologicalProcess'
 'increased_by::Compound:BiologicalProcess'
 'inhibited_by::Disease:Compound' 'activated_by::Disease:Pathway'
 'associated_with::Compound:Gene' 'Unknown::Gene:Compound'
 'increased_by::Compound:Compound'
 'induced_by::BiologicalProcess:Compound'
 'associated_with::Compound:Phenotype'
 'biomarker::Phenotype:BiologicalProcess' 'reduced_by::Metabolite:Pathway'
 'associated_with::Gene:Anatomy' 'treats::BiologicalProcess:Compound']

In [ ]:
#customdb_v20240630
relation_type_map = {
    "inhibited_by::Gene:Compound": "DGIDB::INHIBITOR::Gene:Compound",
    "increased_by::Gene:Compound": "GNBR::E+::Compound:Gene",
    "increased_by::BiologicalProcess:Disease": None,
    "associated_with::Pathway:Disease": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "increased_by::Metabolite:Compound": None,
    "associated_with::Pathway:Metabolite": None,
    "reduced_by::Gene:Compound": "GNBR::E-::Compound:Gene",
    "associated_with::Anatomy:Compound": "biolink::related_to::Anatomy:Compound",
    "associated_with::Disease:Gene": "PrimeKG::associated_with::Disease:Gene",
    "increased_by::Gene:Gene": "GNBR::E+::Gene:Gene",
    "activated_by::Pathway:Gene": "PrimeKG::interacts_with::Pathway:Gene",
    "associated_with::Compound:Disease": "CTD::IS_ASSOCIATED_WITH::Compound:Disease",
    "associated_with::Gene:Compound": "INTACT::ASSOCIATION::Compound:Gene",
    "reduced_by::BiologicalProcess:Disease": "biolink::disrupts::Disease:BiologicalProcess",
    "reduced_by::Gene:Disease": "Hetionet::DdG::Disease:Gene",
    "associated_with::Disease:Compound": "CTD::IS_ASSOCIATED_WITH::Compound:Disease",
    "increased_by::Compound:Disease": "GNBR::J::Compound:Disease",
    "induced_by::Disease:Compound": "PrimeKG::indication::Disease:Compound",
    "activated_by::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "increased_by::Disease:Compound": "GNBR::J::Compound:Disease",
    "upregulated_in::Gene:Gene": "GNBR::E+::Gene:Gene",
    "alleviated_by::Compound:Disease": "GNBR::Pa::Compound:Disease",
    "associated_with::Phenotype:Disease": "biolink::related_to::Phenotype:Disease",
    "downregulated_in::Gene:Compound": "Hetionet::CdG::Compound:Gene",
    "induced_by::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "upregulated_in::Gene:Compound": "Hetionet::CuG::Compound:Gene",
    "inhibited_by::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "associated_with::Metabolite:Disease": None,
    "treats::Compound:Pathway": "CTD::IS_ASSOCIATED_WITH::Compound:Pathway",
    "induced_by::Compound:Disease": "PrimeKG::indication::Compound:Disease",
    "associated_with::Disease:Metabolite": None,
    "downregulated_in::Compound:Pathway": "biolink::participates_in::Compound:Pathway",
    "associated_with::BiologicalProcess:Disease": "CTD::IS_ASSOCIATED_WITH::Disease:BiologicalProcess",
    "biomarker::Compound:Disease": "GNBR::Mp::Compound:Disease",
    "reduced_by::Metabolite:Compound": None,
    "associated_with::Gene:Phenotype": "biolink::has_phenotype::Gene:Phenotype",
    "reduced_by::Compound:Gene": "GNBR::A-::Compound:Gene",
    "associated_with::Metabolite:Compound": None,
    "associated_with::BiologicalProcess:Gene": "PrimeKG::interacts_with::Gene:BiologicalProcess",
    "activated_by::Compound:Pathway": "biolink::participates_in::Compound:Pathway",
    "biomarker::Metabolite:Pathway": None,
    "associated_with::Phenotype:Gene":  "biolink::has_phenotype::Gene:Phenotype",
    "biomarker::Metabolite:Disease": None,
    "inhibited_by::BiologicalProcess:Disease": "biolink::disrupts::Disease:BiologicalProcess",
    "associated_with::Anatomy:Disease":None,
    "biomarker::Gene:Disease": "CTD::marker/mechanism|therapeutic::Gene:Disease",
    "associated_with::BiologicalProcess:Compound": "biolink::related_to::BiologicalProcess:Compound",   
    "biomarker::BiologicalProcess:Disease": "biolink::caused_by::Disease:BiologicalProcess",
    "biomarker::CellularComponent:Disease": "biolink::caused_by::Disease:CellularComponent",
    "associated_with::Phenotype:BiologicalProcess": "biolink::related_to::Phenotype:BiologicalProcess",
    "biomarker::Disease:BiologicalProcess": "biolink::caused_by::Disease:BiologicalProcess",
    "associated_with::Pathway:BiologicalProcess": None,
    "associated_with::BiologicalProcess:BiologicalProcess": "biolink::related_to::BiologicalProcess:BiologicalProcess",
    "associated_with::CellularComponent:Disease": None,
    "biomarker::MolecularFunction:Phenotype": "biolink::related_to::Phenotype:MolecularFunction",
    "increased_by::Gene:Disease": "GNBR::X::Gene:Disease",
    "associated_with::BiologicalProcess:Metabolite": None,
    "upregulated_in::Compound:Gene": "Hetionet::CuG::Compound:Gene",
    "treats::Compound:BiologicalProcess": "biolink::related_to::BiologicalProcess:Compound",
    "associated_with::Pathway:Compound": "CTD::IS_ASSOCIATED_WITH::Compound:Pathway",
    "biomarker::BiologicalProcess:Phenotype": "biolink::related_to::Phenotype:BiologicalProcess",
    "associated_with::BiologicalProcess:Anatomy": "biolink::related_to::BiologicalProcess:Anatomy",
    "associated_with::Metabolite:Phenotype": None,
    "associated_with::BiologicalProcess:Phenotype": "biolink::related_to::Phenotype:BiologicalProcess",
    "biomarker::Gene:Phenotype": "biolink::has_phenotype::Gene:Phenotype",
    "treats::Compound:Disease": "DRUGBANK::treats::Compound:Disease",
    "associated_with::Metabolite:BiologicalProcess": None,
    "reduced_by::Disease:Compound": "GNBR::Pa::Compound:Disease",
    "activated_by::Compound:Gene": "CTD::increases^activity::Compound:Gene",
    "associated_with::Gene:BiologicalProcess": "PrimeKG::interacts_with::Gene:BiologicalProcess",
    "treats::Metabolite:Disease": None,
    "treats::Compound:Phenotype": "biolink::related_to::Phenotype:Compound",
    "associated_with::Pathway:Phenotype": None,
    "biomarker::Pathway:Disease": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "associated_with::Disease:Pathway": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "associated_with::Disease:Disease": "biolink::related_to::Disease:Disease",
    "associated_with::Gene:Pathway": "CTD::IS_ASSOCIATED_WITH::Gene:Pathway",
    "activated_by::Gene:Compound": "DGIDB::ACTIVATOR::Gene:Compound",
    "associated_with::Disease:BiologicalProcess": "CTD::IS_ASSOCIATED_WITH::Disease:BiologicalProcess",
    "increased_by::Metabolite:Gene": None,
    "alleviated_by::Disease:Compound": "GNBR::Pa::Compound:Disease",
    "increased_by::Pathway:Compound": "CTD::IS_ASSOCIATED_WITH::Compound:Pathway",
    "reduced_by::Metabolite:Disease": None,
    "associated_with::Compound:Compound": "biolink::related_to::Compound:Compound",
    "activated_by::Gene:Gene": "GNBR::V+::Gene:Gene",
    "associated_with::Gene:Disease": "CTD::IS_ASSOCIATED_WITH::Gene:Disease",
    "alleviated_by::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "increased_by::Compound:Pathway":"biolink::participates_in::Compound:Pathway",
    "induced_by::Compound:Pathway": "biolink::participates_in::Compound:Pathway",
    "downregulated_in::Compound:Compound": "DRUGBANK::ddi-interactor-in::Compound:Compound",
    "induced_by::Disease:Disease": "biolink::related_to::Disease:Disease",
    "reduced_by::Gene:Pathway": "Hetionet::GpPW::Gene:Pathway",
    "associated_with::Phenotype:Anatomy": "biolink::related_to::Phenotype:Anatomy",
    "inhibited_by::Pathway:Gene": "PrimeKG::interacts_with::Pathway:Gene",
    "increased_by::Compound:Gene": "GNBR::E+::Compound:Gene",
    "upregulated_in::Gene:Disease": "Hetionet::DuG::Disease:Gene",
    "induced_by::BiologicalProcess:Disease": "biolink::caused_by::Disease:BiologicalProcess",
    "associated_with::Gene:Metabolite": None,
    "treats::Metabolite:Phenotype": None,
    "caused_by::Disease:Compound": "PrimeKG::contraindication::Disease:Compound",
    "inhibited_by::Gene:Gene": "STRING::INHIBITION::Gene:Gene",
    "inhibited_by::Pathway:Pathway": None,
    "associated_with::Metabolite:Anatomy": None,
    "biomarker::Gene:Anatomy": "biolink::expressed_in::Gene:Anatomy",
    "activated_by::Disease:Compound": "PrimeKG::indication::Compound:Disease",
    "biomarker::Gene:Compound": "PrimeKG::target::Gene:Compound",
    "associated_with::Gene:Gene": "INTACT::ASSOCIATION::Gene:Gene",
    "alleviated_by::Gene:Disease": "CTD::therapeutic::Gene:Disease",
    "induced_by::Gene:Compound": "DGIDB::ACTIVATOR::Gene:Compound",
    "induced_by::Disease:Metabolite": None,
    "upregulated_in::Pathway:Disease": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "activated_by::Gene:Pathway": "biolink::participates_in::Gene:Pathway",
    "reduced_by::Compound:Metabolite": None,
    "associated_with::Compound:Anatomy": "biolink::related_to::Anatomy:Compound",
    "inhibited_by::Compound:BiologicalProcess": "biolink::related_to::BiologicalProcess:Compound",
    "upregulated_in::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "associated_with::Compound:Pathway": "CTD::IS_ASSOCIATED_WITH::Compound:Pathway",
    "downregulated_in::Pathway:Compound": "biolink::participates_in::Compound:Pathway",
    "reduced_by::Compound:Disease": "GNBR::Pa::Compound:Disease",
    "biomarker::Metabolite:Compound": None,
    "reduced_by::Disease:Gene": "Hetionet::DdG::Disease:Gene",
    "biomarker::Compound:Metabolite":None,
    "increased_by::Phenotype:Gene": "biolink::has_phenotype::Gene:Phenotype",
    "biomarker::Disease:Gene": "CTD::marker/mechanism|therapeutic::Gene:Disease",
    "inhibited_by::Compound:Pathway": "CTD::IS_ASSOCIATED_WITH::Compound:Pathway",
    "increased_by::Phenotype:Disease": "biolink::related_to::Phenotype:Disease",
    "increased_by::Gene:Phenotype": "biolink::has_phenotype::Gene:Phenotype",
    "associated_with::Anatomy:Phenotype": "biolink::related_to::Anatomy:Phenotype",
    "caused_by::Compound:Compound": "DRUGBANK::ddi-interactor-in::Compound:Compound",
    "increased_by::Compound:Phenotype": "biolink::related_to::Phenotype:Compound",
    "associated_with::Phenotype:Phenotype":  "biolink::subclass_of::Phenotype:Phenotype",
    "biomarker::Anatomy:Disease": "biolink::disease_has_location::Disease:Anatomy",
    "reduced_by::Pathway:Disease": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "increased_by::Metabolite:Disease": None,
    "reduced_by::Metabolite:Phenotype": None,
    "increased_by::Metabolite:Phenotype": None,
    "downregulated_in::Metabolite:Disease": None,
    "caused_by::Gene:Disease": "biolink::contributes_to::Gene:Disease",
    "inhibited_by::Compound:Compound": "DRUGBANK::ddi-interactor-in::Compound:Compound",
    "increased_by::Anatomy:Disease": "biolink::disease_has_location::Disease:Anatomy",
    "associated_with::Compound:CellularComponent": "biolink::related_to::CellularComponent:Compound",
    "induced_by::Phenotype:Disease": "biolink::has_phenotype::Disease:Phenotype",
    "associated_with::Compound:BiologicalProcess": "biolink::related_to::CellularComponent:Compound",
    "induced_by::Pathway:BiologicalProcess": None,
    "induced_by::Compound:BiologicalProcess": "biolink::related_to::BiologicalProcess:Compound",
    "increased_by::Compound:BiologicalProcess": "biolink::related_to::BiologicalProcess:Compound",
    "inhibited_by::Disease:Compound": "GNBR::Pa::Compound:Disease",
    "activated_by::Disease:Pathway": "CTD::IS_ASSOCIATED_WITH::Disease:Pathway",
    "associated_with::Compound:Gene": "INTACT::ASSOCIATION::Compound:Gene",
    "Unknown::Gene:Compound": None,
    "increased_by::Compound:Compound": "DRUGBANK::ddi-interactor-in::Compound:Compound",
    "induced_by::BiologicalProcess:Compound": "biolink::related_to::BiologicalProcess:Compound",
    "associated_with::Compound:Phenotype": "biolink::related_to::Phenotype:Compound",
    "biomarker::Phenotype:BiologicalProcess": "biolink::related_to::Phenotype:BiologicalProcess",
    "reduced_by::Metabolite:Pathway": None,
    "associated_with::Gene:Anatomy": "biolink::related_to::Anatomy:Protein",
    "treats::BiologicalProcess:Compound": "biolink::related_to::BiologicalProcess:Compound",
}

In [18]:
#custom_20240329v
relation_type_map = {
    "increased_by::BiologicalProcess:Disease": "BioMedGPS::E+::Disease:BiologicalProcess",
    "associated_with::Pathway:Disease": "BioMedGPS::AssociatedWith::Pathway:Disease",
    "reduced_by::BiologicalProcess:Disease": "BioMedGPS::E-::Disease:BiologicalProcess",
    "reduced_by::Gene:Disease": "Hetionet::DdG::Disease:Gene",
    "associated_with::Compound:Disease": "GNBR::C::Compound:Disease",
    "associated_with::Symptom:Disease": "HSDN::has_symptom::Disease:Symptom",
    "associated_with::Phenotype:Disease": "HSDN::has_phenotype::Disease:Phenotype",
    "associated_with::Metabolite:Disease": "BioMedGPS::AssociatedWith::Metabolite:Disease",
    "associated_with::BiologicalProcess:Disease": "BioMedGPS::AssociatedWith::BiologicalProcess:Disease",
    "biomarker::Compound:Disease": "GNBR::Mp::Compound:Disease",
    "biomarker::Metabolite:Disease": "BioMedGPS::Biomarker::Metabolite:Disease",
    "inhibited_by::BiologicalProcess:Disease": "BioMedGPS::E-::Disease:BiologicalProcess",
    "associated_with::Anatomy:Disease": "Hetionet::Aa::Anatomy:Disease",
    "biomarker::Gene:Disease": "GNBR::Md::Gene:Disease",
    "biomarker::BiologicalProcess:Disease": None,
    "biomarker::CellularComponent:Disease": None,
    "biomarker::Disease:BiologicalProcess": None,
    "associated_with::CellularComponent:Disease": "BioMedGPS::AssociatedWith::CellularComponent:Disease",
    "treats::Compound:Disease": "DRUGBANK::treats::Compound:Disease",
    "treats::Metabolite:Disease": "DRUGBANK::treats::Metabolite:Disease",
    "associated_with::Disease:Compound": "GNBR::C::Compound:Disease",
    "biomarker::Pathway:Disease": "BioMedGPS::AssociatedWith::Pathway:Disease",
    "associated_with::Disease:BiologicalProcess": "BioMedGPS::AssociatedWith::Disease:BiologicalProcess",
    "reduced_by::Metabolite:Disease": "BioMedGPS::E-::Disease:Metabolite",
    "induced_by::BiologicalProcess:Disease": "BioMedGPS::E+::Disease:BiologicalProcess",
    "increased_by::Symptom:Disease": "HSDN::has_symptom::Disease:Symptom",
    "increased_by::Phenotype:Disease": "HSDN::has_phenotype::Disease:Phenotype",
    "biomarker::Anatomy:Disease": None,
    "reduced_by::Pathway:Disease": "BioMedGPS::E-::Disease:Pathway",
    "increased_by::Metabolite:Disease": "BioMedGPS::E+::Disease:Metabolite",
    "downregulated_in::Metabolite:Disease": "BioMedGPS::E-::Disease:Metabolite",
    "increased_by::Anatomy:Disease": None,
    "reduced_by::Compound:Disease": "GNBR::C::Compound:Disease",
}

,relation_type,source_name,source_type,source_id,target_name,target_type,target_id,key_sentence,pmid,idx
0,inhibited_by::Gene:Compound,MnSOD,Gene,ENTREZ:20656,PM2.5,Compound,MESH:D052638,PM2.5 inhibited Mn superoxide dismutase (MnSOD...,25560372,0
1,increased_by::Gene:Compound,TNF-α,Gene,ENTREZ:21926,PM,Compound,MESH:D052638,The results found that PM mice displayed highe...,32270451,1
5,increased_by::BiologicalProcess:Disease,mucosal associated invariant T cells (MAIT) cell,BiologicalProcess,GO:0002403,ME/CFS,Disease,MONDO:0005404,"Conversely, there was a significantly increase...",31057538,5
6,associated_with::Pathway:Disease,kynurenine pathway (KP),Pathway,KEGG:hsa00380,ME/CFS,Disease,MONDO:0005404,"Hyperactivation of the KP, whether compensator...",35656104,6
20,increased_by::Metabolite:Compound,MDA,Metabolite,HMDB:HMDB0006112,PM2.5,Compound,MESH:D052638,PM2.5 inhibited Mn superoxide dismutase (MnSOD...,25560372,20
...,...,...,...,...,...,...,...,...,...,...
2310,associated_with::Gene:Anatomy,IFN-γ,Gene,ENTREZ:3458,pulmonary function,Anatomy,MESH:D008168,"Notably, therapeutic neutralization of IFN-γ a...",37745354,2310
2314,associated_with::BiologicalProcess:Disease,menstrual cycle,BiologicalProcess,GO:0042703,COVID-19,Disease,MONDO:0100096,The association between the COVID-19 and incre...,37974147,2314
2316,treats::BiologicalProcess:Compound,inflammatory responses,BiologicalProcess,GO:0006954,imatinib,Compound,DrugBank:DB00619,COVID-19 is characterized by an alveolar cytok...,37530975,2316
2317,associated_with::BiologicalProcess:Compound,NF-κB signaling,BiologicalProcess,GO:0038061,imatinib,Compound,DrugBank:DB00619,COVID-19 is characterized by an alveolar cytok...,37530975,2317
2318,associated_with::BiologicalProcess:Anatomy,inflammatory responses,BiologicalProcess,GO:0006954,alveolar,Anatomy,UBERON:0002169,COVID-19 is characterized by an alveolar cytok...,37530975,2318

In [16]:
print(
    invalid_relations[
        invalid_relations["relation_type"] == "associated_with::Gene:Anatomy"
    ]
)

                      relation_type source_name source_type    source_id  \
2283  associated_with::Gene:Anatomy       IFN-γ        Gene  ENTREZ:3458
2304  associated_with::Gene:Anatomy         TNF        Gene  ENTREZ:7124
2305  associated_with::Gene:Anatomy       IL-1β        Gene  ENTREZ:3553
2308  associated_with::Gene:Anatomy       IL-1β        Gene  ENTREZ:3553
2309  associated_with::Gene:Anatomy         TNF        Gene  ENTREZ:7124
2310  associated_with::Gene:Anatomy       IFN-γ        Gene  ENTREZ:3458

                target_name target_type       target_id  \
2283  alveolar regeneration     Anatomy  UBERON:0002169
2304  alveolar regeneration     Anatomy  UBERON:0002169
2305     pulmonary function     Anatomy    MESH:D008168
2308  alveolar regeneration     Anatomy  UBERON:0002169
2309     pulmonary function     Anatomy    MESH:D008168
2310     pulmonary function     Anatomy    MESH:D008168

                                           key_sentence      pmid   idx
2283  Notably, therapeutic neutralization of IFN-γ a...  37745354  2283
2304  Notably, therapeutic neutralization of IFN-γ a...  37745354  2304
2305  Notably, therapeutic neutralization of IFN-γ a...  37745354  2305
2308  Notably, therapeutic neutralization of IFN-γ a...  37745354  2308
2309  Notably, therapeutic neutralization of IFN-γ a...  37745354  2309
2310  Notably, therapeutic neutralization of IFN-γ a...  37745354  2310

### Merge the formatted relations into one file

In [40]:
import pandas as pd

files = [
    "./formatted_customdb_v20240630.tsv",
    "./formatted_fuscc_bcdb_v20240923.tsv",
    "./formatted_malacards_mecfs.tsv",
    "./formatted_treatme_survey_compounds.tsv",
    "./formatted_treatme_survey_phenotypes.tsv",
    "./20250728版/merged_knowledges_matchreltiontype.tsv"
]
merged = pd.concat([pd.read_csv(f, sep="\t") for f in files], ignore_index=True)
merged.to_csv("formatted_merged_all.tsv", sep="\t", index=False)

0       False
1       False
2       False
3       False
4       False
        ...
5876    False
5877    False
5878    False
5879    False
5880    False
Name: relation_type, Length: 5881, dtype: bool

In [41]:
import os
import os.path as osp
import subprocess


def format_customdb(filename):
    def get_project_root():
        try:
            return osp.dirname(osp.dirname(os.getcwd()))
        except Exception as e:
            raise RuntimeError(f"Failed to determine project root: {e}")

    try:
        root_dir = get_project_root()
        print(f"Project root directory: {root_dir}")
    except RuntimeError as e:
        print(e)
        exit(1)

    database = "customdb"
    relations_path = osp.join(
        root_dir,
        "relations",
        "customdb",
        filename,
    )
    output_dir = osp.join(root_dir, "formatted_relations", "customdb")
    entities_path = osp.join(root_dir, "entities.tsv")
    log_file = osp.join(output_dir, "log.txt")
    relation_types_file = osp.join(root_dir, "relation_types.tsv")

    command = [
        "graph-builder",
        "--database",
        database,
        "-d",
        relations_path,
        "-o",
        output_dir,
        "-f",
        entities_path,
        "-n",
        "20",
        "--download",
        "--skip",
        "-l",
        log_file,
        "--debug",
        "--relation-type-dict-fpath",
        relation_types_file,
    ]

    print("Executing command:", " ".join(command))

    try:
        subprocess.run(command, check=True)
    except FileNotFoundError:
        print(
            "Error: 'graph-builder' command not found. Make sure it is installed and available in the PATH."
        )
        exit(1)
    except subprocess.CalledProcessError as e:
        print(f"Error: Command execution failed with return code {e.returncode}")
        print(f"Output: {e.output}")
        exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        exit(1)

In [42]:
format_customdb("formatted_merged_all.tsv")

Project root directory: /Users/zhuzhixing/KG/biomedgps-data/graph_data
Executing command: graph-builder --database customdb -d /Users/zhuzhixing/KG/biomedgps-data/graph_data/relations/customdb/formatted_merged_all.tsv -o /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb -f /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv -n 20 --download --skip -l /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/log.txt --debug --relation-type-dict-fpath /Users/zhuzhixing/KG/biomedgps-data/graph_data/relation_types.tsv

2025-07-31 14:42:16 - cli:171 - INFO - Run jobs with (output_dir: /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb, db file/directory: /Users/zhuzhixing/KG/biomedgps-data/graph_data/relations/customdb/formatted_merged_all.tsv, databases: ('customdb',), download: True, skip: True)
2025-07-31 14:42:19 - base_parser:229 - INFO - Using allow_ignore_checking_errors=all to ignore the checking errors.
2025-07-31 14:42:19 - customdb_parser:100 - INFO - Get 5881 relations
2025-07-31 14:42:20 - base_parser:478 - INFO - Found 5881 relations.
2025-07-31 14:42:20 - base_parser:787 - INFO - Found entity id map file, skip to generate it. If you want to regenerate it, please delete the file: /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/customdb.entity_id_map.json
2025-07-31 14:42:20 - base_parser:480 - INFO - Found 96758 entity ids in entity id map.
2025-07-31 14:42:20 - base_parser:494 - INFO - The number of relations before dropna: 5881
2025-07-31 14:42:20 - base_parser:496 - INFO - The number of relations after dropna: 5881
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.00%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.05%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.09%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.14%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.19%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.23%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.28%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.32%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.37%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.42%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.46%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.51%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.56%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.60%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.65%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.69%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.74%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.79%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.83%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.88%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.93%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 0.97%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.02%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.06%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.11%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.16%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.20%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.25%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.30%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.34%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.39%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.43%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.48%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.53%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.57%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.62%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.67%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.71%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.76%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.80%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.85%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.90%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.94%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 1.99%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.04%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.08%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.13%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.17%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.22%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.27%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.31%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.36%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.41%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.45%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.50%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.55%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.59%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.64%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.68%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.73%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.78%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.82%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.87%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.92%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 2.96%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.01%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.05%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.10%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.15%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.19%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.24%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.29%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.33%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.38%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.42%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.47%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.52%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.56%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.61%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.66%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.70%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.75%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.79%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.84%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.89%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.93%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 3.98%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.03%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.07%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.12%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.16%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.21%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.26%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.30%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.35%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.40%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.44%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.49%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.53%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.58%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.63%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.67%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.72%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.77%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.81%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.86%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.91%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 4.95%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.00%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.04%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.09%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.14%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.18%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.23%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.28%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.32%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.37%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.41%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.46%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.51%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.55%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.60%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.65%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.69%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.74%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.78%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.83%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.88%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.92%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 5.97%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.02%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.06%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.11%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.15%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.20%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.25%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.29%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.34%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.39%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.43%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.48%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.52%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.57%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.62%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.66%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.71%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.76%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.80%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.85%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.89%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.94%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 6.99%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.03%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.08%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.13%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.17%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.22%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.27%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.31%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.36%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.40%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.45%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.50%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.54%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.59%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.64%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.68%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.73%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.77%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.82%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.87%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.91%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 7.96%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.01%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.05%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.10%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.14%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.19%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.24%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.28%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.33%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.38%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.42%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.47%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.51%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.56%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.61%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.65%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.70%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.75%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.79%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.84%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.88%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.93%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 8.98%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.02%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.07%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.12%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.16%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.21%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.25%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.30%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.35%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.39%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.44%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.49%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.53%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.58%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.63%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.67%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.72%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.76%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.81%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.86%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.90%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 9.95%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.00%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.04%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.09%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.13%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.18%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.23%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.27%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.32%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.37%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.41%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.46%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.50%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.55%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.60%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.64%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.69%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.74%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.78%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.83%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.87%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.92%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 10.97%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.01%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.06%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.11%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.15%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.20%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.24%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.29%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.34%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.38%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.43%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.48%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.52%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.57%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.61%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.66%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.71%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.75%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.80%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.85%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.89%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.94%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 11.99%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.03%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.08%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.12%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.17%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.22%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.26%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.31%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.36%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.40%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.45%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.49%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.54%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.59%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.63%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.68%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.73%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.77%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.82%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.86%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.91%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 12.96%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.00%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.05%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.10%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.14%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.19%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.23%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.28%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.33%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.37%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.42%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.47%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.51%
2025-07-31 14:42:20 - base_parser:504 - INFO - Processing 13.56%

In [41]:
ls /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb

customdb.entity_id_map.json        raw_customdb.tsv
duplicated_customdb.tsv            unformatted_customdb.tsv
formatted_customdb.tsv             unformatted_customdb_entities.tsv
log.txt